---
title: "Understand Your Donor Base"
description: Analyzing the size of a donor base over time
date: 01-01-2018
output:
    distill::distill_article:
        self_contained: false
---

In this project, the organization was concerned about their shrinking donations.\
Initial analysis suggested that although the donations per donor were steady, that perhaps the donor base was shrinking.\
Further analysis looked at the size of the pool of donors, and grouped them into categories of 'new' and 'lapsed'.\
A plot of the cumulative number of each group confirms the suspicion.

```{r, echo=FALSE}
library(tidyverse)

df <- structure(list(
  yr = c( 2000, 1999, 1998, 1997, 1996, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015), 
  arr = c(1225,  312,   87,   65,   69, 1532, 1563, 1647, 1669, 1697, 1698, 1762, 1796, 1807, 1808, 1826, 1837, 1945, 1950, 1960), 
  dep = c( 650,  108,   26,    0,   10,  661,  972, 1267, 1270, 1372, 1384, 1492, 1537, 1630, 1638, 1685, 1748, 1788, 1836, 2021)
  ), 
  row.names = c( NA, -20L), 
  class = c("tbl_df", "tbl", "data.frame")
  )

df %>%
  pivot_longer(names_to = "varn", values_to = "val", cols = -yr) %>%
  ggplot(aes(x = yr, y = val, colour = varn)) +
  geom_point() +
  ggthemes::scale_color_colorblind() +
  theme_minimal() +
  labs(
    x = "", y = "Donors", title = "Donor Pool is Shrinking"
  ) +
  scale_y_continuous(labels = scales::comma) +
  theme(legend.position = "none") +
  annotate(geom = "text", x = 2000, y = 1750, label = "New Donors", colour = "darkgreen") +
  annotate(geom = "text", x = 2010, y = 1250, label = "Lapsed Donors", colour = "red") +
  scale_color_manual(values = c("darkgreen", "red"))
```

In the early 2000's, there were many more new donors than lapsed donors. But as we progress we find that there are fewer new donors and more lapsed donors each year. In 2015 there were more lapsed donors than new donors for the first time.

Although the details of this plot depend on how 'new donor' and 'lapsed donor' are defined, changing these definitions somewhat has little effect on the conclusion: the donor pool is shrinking.

This finding allowed the organization to focus its efforts in three areas:

-   acquiring more new donors,

-   recapturing lapsed donors,

-   preventing donors from lapsing

We can also perform customer lifetime value (CLV) analyses that can help you assess the value of each customer to your business over the long term.

